# Generated by Django 2.2.1 on 2019-05-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False, verbose_name='Id do Aluno')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobre Nome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('rg', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rg/Registro')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(blank=True, choices=[('FEM', 'Feminino'), ('MASC', 'Masculino')], max_length=4, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Altura')),
                ('peso', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Peso')),
                ('tipo_sanguinio', models.CharField(blank=True, max_length=11, null=True, verbose_name='Tipo Sanguinio')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fone1', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('fone2', models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular')),
                ('fone3', models.CharField(blank=True, max_length=14, null=True, verbose_name='Whatsapp')),
                ('pai', models.CharField(blank=True, max_length=100, null=True)),
                ('fone4', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mãe')),
                ('fone5', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('estado', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rua', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='aluno/images/', verbose_name='Foto')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aluno.Aluno')),
                ('alegia', models.CharField(blank=True, max_length=200, null=True)),
                ('ferimento', models.CharField(blank=True, max_length=200, null=True)),
                ('sente_sintomas', models.CharField(blank=True, max_length=200, null=True)),
                ('s_dores_pulmonares', models.CharField(blank=True, max_length=200, null=True)),
                ('fazendo_tratamento', models.CharField(blank=True, max_length=200, null=True)),
                ('emergencia_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('emergencia_telefone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aluno.Aluno')),
                ('num_matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricula')),
                ('professor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Professor')),
            ],
        ),
    ]
