# Generated by Django 2.2 on 2019-04-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereços',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaisResponsaveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False, verbose_name='Id do Aluno')),
                ('num_matricula', models.CharField(blank=True, max_length=50, verbose_name='Matricula')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobre Nome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('rg', models.CharField(blank=True, max_length=50, verbose_name='RG/Certidão de nascimento')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('sexo', models.CharField(blank=True, choices=[('FEM', 'Feminino'), ('MASC', 'Masculino')], max_length=4, verbose_name='Sexo')),
                ('altuna', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Altura')),
                ('peso', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, verbose_name='Peso')),
                ('tipo_sanguinio', models.CharField(blank=True, max_length=11, verbose_name='Tipo Sanguinio')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('data_atualização', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('endereco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.Endereços', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Alunos',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
