# Generated by Django 2.2 on 2019-05-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='img',
            field=models.ImageField(blank=True, upload_to='_imagens/'),
        ),
    ]
