# Generated by Django 2.2 on 2019-09-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(default=0, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
