# Generated by Django 2.2 on 2019-04-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='altuna',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.Endereços', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RG/Certidão de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('FEM', 'Feminino'), ('MASC', 'Masculino')], max_length=4, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tipo_sanguinio',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Tipo Sanguinio'),
        ),
    ]
