# Generated by Django 2.2 on 2019-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20190424_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='altuna',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='data_atualização',
            new_name='data_atualizacão',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='endereco',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cep'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.IntegerField(blank=True, null=True, verbose_name='RG/Certidão de nascimento'),
        ),
    ]
