# Generated by Django 2.2 on 2019-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20190512_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='img',
            field=models.ImageField(blank=True, upload_to='aluno/images/', verbose_name='Foto'),
        ),
    ]
