# Generated by Django 2.2 on 2019-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_aluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='fone1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='fone2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='fone3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='fone4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='fone5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='mãe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
