# Generated by Django 2.2 on 2019-04-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_auto_20190425_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='fone1',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='fone2',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='fone3',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='fone4',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='fone5',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RG/Certidão de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('FEM', 'Feminino'), ('MASC', 'Masculino')], max_length=4, null=True),
        ),
    ]
