# Generated by Django 2.2 on 2019-04-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_auto_20190425_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bolsa',
            field=models.BooleanField(default=False, max_length=5, verbose_name='Bolsista'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'inativo')], default=True, max_length=5, verbose_name='Situação Cadastral'),
        ),
    ]
