# Generated by Django 2.2 on 2019-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_auto_20190425_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bolsa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, max_length=5, verbose_name='Bolsista'),
        ),
    ]
