# Generated by Django 2.2 on 2019-04-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_auto_20190425_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaisResponsaveis',
            new_name='dadosEscolinha',
        ),
        migrations.DeleteModel(
            name='Endereços',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='bolsa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='status',
        ),
        migrations.AddField(
            model_name='aluno',
            name='escolinha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.dadosEscolinha'),
        ),
    ]
