# Generated by Django 2.2 on 2019-04-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_auto_20190425_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
    ]
